server:
  port: ${SERVICE_CONTAINER_PORT:8080}
  servlet:
      context-path: ${SERVICE_CONTEXT_PATH:/}
spring:
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
      jakarta:
        persistence:
            sharedCache:
                mode: UNSPECIFIED
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
  profiles:
    default: localdb, common

logging:
  file:
    name: ${LOG_FILE_NAME:logs/app.log}
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        web:  ${LOG_LEVEL:INFO}

jwt:
  issuer: ${JWT_ISSUER}
  secret: ${JWT_SECRET}
