server:
  port: ${SERVICE_CONTAINER_PORT}
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      jakarta:
        persistence:
            sharedCache:
                mode: UNSPECIFIED
    open-in-view: false


  profiles:
    default: localdb