ALTER TABLE VRUSERS DROP CONSTRAINT VRUSERS_ibfk_1;
ALTER TABLE VRUSERS DROP COLUMN ADDRESS_ID;

DROP TABLE VRADDRESSES;

ALTER TABLE VRUSERS DROP COLUMN NAME;
ALTER TABLE VRUSERS DROP COLUMN GENRE;
ALTER TABLE VRUSERS DROP COLUMN BIRTHDATE;
ALTER TABLE VRUSERS DROP COLUMN ABOUT;
