CREATE TABLE VRADDRESSES
(
    ID      VARCHAR(36),
    USER_ID VARCHAR(36),
    COUNTRY VARCHAR(128),
    CITY    VARCHAR(255),
    ZIP     VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE ROLES
(
    NAME VARCHAR(128),
    PRIMARY KEY (NAME)
);

CREATE TABLE VRUSERS
(
    ID         VARCHAR(36)  NOT NULL,
    NAME       VARCHAR(128) NOT NULL,
    USERNAME   VARCHAR(256) NOT NULL,
    EMAIL      VARCHAR(128) NOT NULL,
    GENRE      VARCHAR(64)  NOT NULL,
    PASSWORD   VARCHAR(1028),
    ADDRESS_ID VARCHAR(36),
    BIRTHDATE  DATE,
    ABOUT      VARCHAR(2048),
    PRIMARY KEY (ID),
    UNIQUE (USERNAME),
    UNIQUE (EMAIL),
    FOREIGN KEY (ADDRESS_ID) REFERENCES VRADDRESSES (ID) ON DELETE SET NULL
);

ALTER TABLE VRADDRESSES ADD CONSTRAINT FK_VRADDRESSES_VRUSERS FOREIGN KEY (USER_ID) REFERENCES VRUSERS (ID) ON DELETE CASCADE;

CREATE TABLE VRUSERS_ROLES
(
    USER_ID VARCHAR(36),
    ROLE_NAME VARCHAR(36),
    PRIMARY KEY (USER_ID, ROLE_NAME),
    FOREIGN KEY (USER_ID) REFERENCES VRUSERS (ID) ON DELETE CASCADE,
    FOREIGN KEY (ROLE_NAME) REFERENCES ROLES (NAME) ON DELETE CASCADE
);

INSERT INTO ROLES (NAME) VALUES ('SORCERER_SUPREME');
INSERT INTO ROLES (NAME) VALUES ('ADMIN');
INSERT INTO ROLES (NAME) VALUES ('USER');