CREATE TABLE VRADDRESSES
(
    ID      VARCHAR(36),
    COUNTRY VARCHAR(128),
    CITY    VARCHAR(255),
    ZIP     VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE VRUSERS
(
    ID         VARCHAR(36)  NOT NULL,
    NAME       VARCHAR(128) NOT NULL,
    USERNAME   VARCHAR(256) NOT NULL,
    EMAIL      VARCHAR(128) NOT NULL,
    GENRE      VARCHAR(64)  NOT NULL,
    PASSWORD   VARCHAR(1028),
    ADDRESS_ID VARCHAR(36)  NOT NULL,
    BIRTHDATE  DATE,
    ABOUT      VARCHAR(2048),
    CREATED    TIMESTAMP,
    UPDATED    TIMESTAMP,
    VERSION    INTEGER,
    PRIMARY KEY (ID),
    UNIQUE (USERNAME),
    UNIQUE (EMAIL),
    FOREIGN KEY (ADDRESS_ID) REFERENCES VRADDRESSES (ID)
);