CREATE TABLE DEVICE_AUTHENTICATION
(
    ID VARCHAR(36) NOT NULL,
    USER_ID VARCHAR(36),
    CLIENT_ID VARCHAR(36) NOT NULL,
    DEVICE_CODE VARCHAR(36) NOT NULL UNIQUE,
    USER_CODE VARCHAR(36) NOT NULL UNIQUE,
    EXPIRATION_DATE TIMESTAMP NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (USER_ID) REFERENCES VRUSERS(ID)
)